### ISSUE TITLE
Hiding both dock and status bar icons doesn't work

### ISSUE THREAD

**Issue by jakajancar** [adur1990/Passafari#16]
Catalina (10.15.1)

  - Enable both, both work. Restart app, both work, all good.
  - Enable dock only, it works, status bar hidden. Restart app, same situation, all good.
  - Enable status bar only, it works, dock hidden. Restart app, dock appears momentarily, then only status bar remains, all good.
  - Disable both, both gone. Restart app, dock appears momentarily, status bar is visible but no action on click, both before and after closing dialog.

So you can hide them both, but after restart, status bar icon is still there, though non-functional.

**Comment by jakajancar** [comment]
And also just noticed, location services indicator keeps appearing *over* it:

<img width="51" alt="Screen Shot 2019-11-15 at 2 28 13 PM" src="https://user-images.githubusercontent.com/187741/68970080-7b28ca80-07b4-11ea-90d3-5da7aba239b8.png">

(but only if both disabled, with status bar icon enabled, it works OK)

So it's in this weird phantom state.

I don't think you can hide both, and tbh as annoying having to have the icon is, having neither is something you don't expect from a Mac app.

**Comment by adur1990** [comment]
Oh wow, this is interesting. And your suggestion about having either of the both always enabled was an idea I also had. Versions < 0.4 required some settings, this is why I decided to have a window based host app. But since version 0.4, I think there is really no need anymore for a dedicated window. I think I will remove the window altogether and have the host app living as a status bar app that simply shows a popover, which says “don’t close this app“. This will make the dock icon obsolete and the status bar item will always be present.

What do you think about this idea?

**Comment by jakajancar** [comment]
Yup, I think status bar is the place for such "service" apps and this simplifies the app. I like it.

**Comment by jakajancar** [comment]
You could also just show the password search box there? E.g. for looking up non-web passwords.

**Comment by adur1990** [comment]
The idea of showing the search field in the Status Bar makes me think. What should that be good for? One could possibly implement the functionality that pass -c <password> offers there. But you always have to search first. Isn't it faster to open a terminal? I have a global shortcut for my terminal, it wouldn't do me much good. How is it with others or with you? I can't think of any other purpose.

**Comment by adur1990** [comment]
Sorry, issue closed by mistake :D

**Comment by jakajancar** [comment]
Actually, now that I think of it, the only case where I would use this is for the rare times when I use Chrome, but for that I should just install the Chrome extension :) I imagine some people might have some other passwords, but it's not like you can get away from using CLI anyways.

It also seemed like a nice filler to put *something* there.

But on second thought, just a "don't close me" is simplest and best.

**Comment by adur1990** [comment]
So I thought about the following: The suggested search is displayed in the status bar and when I choose a password, only the first line is copied to the clipboard, just like `pass -c <password>`. But to make it more useful, I'll add the same shortcut that the Safari extension uses, `shift-alt-p`, to call the search field. When I am in Safari, the password and username are filled in automatically using the shortcut. If I'm not in Safari, the app opens in the status bar. This provides a very quick way to copy the password to the clipboard.  I stumbled across some occasions where this feature would speed up my workflow. This not only makes the host app available in the status bar and annoys people, but it also gives it some meaning. I've already started the implementation, the next release is on the horizon 😄 

Thank you for your help. Would you mind if I added you to the README as a contributor and inspiration for this feature?
