### ISSUE TITLE
Invalid s2k specifier

### ISSUE THREAD

**Issue by jakajancar** [adur1990/Passafari#7]
I went through the wizard, then upon launching the app I get a crash report:

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid s2k specifier'
abort() called
```

(key has no passphrase)

**Comment by adur1990** [comment]
Hi, sorry for the late reply. Could you give me more details about what exactly crashed?

Did you store your passphrase in the macOS keychain?
Does the entire app crash?
What OS version are you using?
Which passwordstore version are you using?
Did you built Passafari yourself or are you using a release?

`Invalid s2k specifier` is an error thrown by a third-party library I'm using, [ObjectivePGP](https://github.com/krzyzanowskim/ObjectivePGP) related to ECC keys.
Are you using a RSA or ECC key for your passwords?

**Comment by jakajancar** [comment]
Hey,

v0.3.2-beta from GitHub releases. Pass version 1.7.3.
Yes, entire app crashes.
No passphrase.
I select `~/.password-store` and `~/.gnupg` directories (not the `~/.gnupg/.passafari-private` file - I cannot select that).

**Comment by adur1990** [comment]
Hi,

okay, that sounds perfectly fine. Are you using and RSA or ECC key?

**Comment by jakajancar** [comment]
I use a ECC key

**Comment by adur1990** [comment]
I found the problem. The library I'm using, [ObjectivePGP](https://github.com/krzyzanowskim/ObjectivePGP) does currently not support ECC. For now, there is no fix for that, sorry.

I will keep this issue open and see if I can find a workaround, sorry.

**Comment by adur1990** [comment]
So, I updated Passafari. Please update to version 0.4 and give it a try now. Please read the instructions at the beginning of the readme.

I will close the issue for now. If your problem is not solved yet, reopen this issue.

**Comment by jakajancar** [comment]
Very cool, works now!
Also great on getting rid of the sandbox, the consequences were definitely not worth it.
